MAX_TURNS = 25


ROBOT_GREEN = 0
ROBOT_BLUE = 1
ROBOT_YELLOW = 2
ROBOT_RED = 3
ROBOTS = (ROBOT_GREEN, ROBOT_BLUE, ROBOT_YELLOW, ROBOT_RED)

ROBOT_TO_COLORS = {ROBOT_GREEN: "GREEN", ROBOT_BLUE: "BLUE", ROBOT_YELLOW: "YELLOW", ROBOT_RED: "RED"}


GOAL_ANY = "Any"
GOAL_GREEN_PLANET = "Green planet"
GOAL_BLUE_PLANET = "Blue planet"
GOAL_YELLOW_PLANET = "Yellow planet"
GOAL_RED_PLANET = "Red planet"
GOAL_GREEN_COGS = "Green cog"
GOAL_BLUE_COGS = "Blue cog"
GOAL_YELLOW_COGS = "Yellow cog"
GOAL_RED_COGS = "Red cog"
GOAL_GREEN_CIRCLE = "Green circle"
GOAL_BLUE_CIRCLE = "Blue circle"
GOAL_YELLOW_CIRCLE = "Yellow circle"
GOAL_RED_CIRCLE = "Red circle"
GOAL_GREEN_CROSS = "Green cross"
GOAL_BLUE_CROSS = "Blue cross"
GOAL_YELLOW_CROSS = "Yellow  cross"
GOAL_RED_CROSS = "Red cross"

GOALS = (
    GOAL_ANY,
    GOAL_GREEN_PLANET,
    GOAL_BLUE_PLANET,
    GOAL_YELLOW_PLANET,
    GOAL_RED_PLANET,
    GOAL_GREEN_COGS,
    GOAL_BLUE_COGS,
    GOAL_YELLOW_COGS,
    GOAL_RED_COGS,
    GOAL_GREEN_CIRCLE,
    GOAL_BLUE_CIRCLE,
    GOAL_YELLOW_CIRCLE,
    GOAL_RED_CIRCLE,
    GOAL_GREEN_CROSS,
    GOAL_BLUE_CROSS,
    GOAL_YELLOW_CROSS,
    GOAL_RED_CROSS,
)

GOALS_PLANET = (GOAL_GREEN_PLANET, GOAL_BLUE_PLANET, GOAL_YELLOW_PLANET, GOAL_RED_PLANET)
GOALS_COGS = (GOAL_GREEN_COGS, GOAL_BLUE_COGS, GOAL_YELLOW_COGS, GOAL_RED_COGS)
GOALS_CIRCLE = (GOAL_GREEN_CIRCLE, GOAL_BLUE_CIRCLE, GOAL_YELLOW_CIRCLE, GOAL_RED_CIRCLE)
GOALS_CROSS = (GOAL_GREEN_CROSS, GOAL_BLUE_CROSS, GOAL_YELLOW_CROSS, GOAL_RED_CROSS)

# GOALS_TO_COLOR = {
#     GOALS_GREEN": (GOAL_GREEN_PLANET, GOAL_GREEN_COGS, GOAL_GREEN_CIRCLE, GOAL_GREEN_CROSS)
#     GOALS_BLUE": (GOAL_BLUE_PLANET, GOAL_BLUE_COGS, GOAL_BLUE_CIRCLE, GOAL_BLUE_CROSS)
#     GOALS_YELLOW": (
#         GOAL_YELLOW_PLANET,
#         GOAL_YELLOW_COGS,
#         GOAL_YELLOW_CIRCLE,
#         GOAL_YELLOW_CROSS,
#     )
#     GOALS_RED": (GOAL_RED_PLANET, GOAL_RED_COGS, GOAL_RED_CIRCLE, GOAL_RED_CROSS)

# }


GOAL_TO_ROBOT = {
    GOAL_GREEN_PLANET: ROBOT_GREEN,
    GOAL_BLUE_PLANET: ROBOT_BLUE,
    GOAL_YELLOW_PLANET: ROBOT_YELLOW,
    GOAL_RED_PLANET: ROBOT_RED,
    GOAL_GREEN_COGS: ROBOT_GREEN,
    GOAL_BLUE_COGS: ROBOT_BLUE,
    GOAL_YELLOW_COGS: ROBOT_YELLOW,
    GOAL_RED_COGS: ROBOT_RED,
    GOAL_GREEN_CIRCLE: ROBOT_GREEN,
    GOAL_BLUE_CIRCLE: ROBOT_BLUE,
    GOAL_YELLOW_CIRCLE: ROBOT_YELLOW,
    GOAL_RED_CIRCLE: ROBOT_RED,
    GOAL_GREEN_CROSS: ROBOT_GREEN,
    GOAL_BLUE_CROSS: ROBOT_BLUE,
    GOAL_YELLOW_CROSS: ROBOT_YELLOW,
    GOAL_RED_CROSS: ROBOT_RED,
}


GOAL_TO_COLORS = {
    GOAL_GREEN_PLANET: "GREEN",
    GOAL_BLUE_PLANET: "BLUE",
    GOAL_YELLOW_PLANET: "YELLOW",
    GOAL_RED_PLANET: "RED",
    GOAL_GREEN_COGS: "GREEN",
    GOAL_BLUE_COGS: "BLUE",
    GOAL_YELLOW_COGS: "YELLOW",
    GOAL_RED_COGS: "RED",
    GOAL_GREEN_CIRCLE: "GREEN",
    GOAL_BLUE_CIRCLE: "BLUE",
    GOAL_YELLOW_CIRCLE: "YELLOW",
    GOAL_RED_CIRCLE: "RED",
    GOAL_GREEN_CROSS: "GREEN",
    GOAL_BLUE_CROSS: "BLUE",
    GOAL_YELLOW_CROSS: "YELLOW",
    GOAL_RED_CROSS: "RED",
}


WALL_UP = 0
WALL_RIGHT = 1
WALL_DOWN = 2
WALL_LEFT = 3
WALLS = (WALL_UP, WALL_RIGHT, WALL_DOWN, WALL_LEFT)

CASE_WALLS = (WALL_RIGHT, WALL_DOWN)


DIRECTION_UP = 0
DIRECTION_RIGHT = 1
DIRECTION_DOWN = 2
DIRECTION_LEFT = 3
DIRECTIONS = (DIRECTION_UP, DIRECTION_RIGHT, DIRECTION_DOWN, DIRECTION_LEFT)
